version: '3.8'

services:
  app:
    build: .
    ports:
      - "3050:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
